package com.TREC.Analyzers;

import java.util.Arrays;
import java.util.List;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.TokenStream;
import org.apache.lucene.analysis.Tokenizer;
import org.apache.lucene.analysis.Analyzer.TokenStreamComponents;
import org.apache.lucene.analysis.core.LowerCaseFilter;
import org.apache.lucene.analysis.core.StopAnalyzer;
import org.apache.lucene.analysis.core.StopFilter;
import org.apache.lucene.analysis.en.EnglishPossessiveFilter;
import org.apache.lucene.analysis.en.PorterStemFilter;
import org.apache.lucene.analysis.standard.StandardFilter;
import org.apache.lucene.analysis.standard.StandardTokenizer;
import org.tartarus.snowball.ext.EnglishStemmer;

public class EnglishStopAnalyzer extends Analyzer{
	@Override
	protected TokenStreamComponents createComponents(String arg0) {
		 final Tokenizer source = new StandardTokenizer();
		    TokenStream result = new StandardFilter(source);
		    result = new EnglishPossessiveFilter(result);
		    result = new LowerCaseFilter(result);
		    List<String> stopList = Arrays.asList("i" , 
		    		"me" , 
		    		"my" , 
		    		"myself" , 
		    		"we" , 
		    		"our" , 
		    		"ours" , 
		    		"ourselves" , 
		    		"you" , 
		    		"your" , 
		    		"yours" , 
		    		"yourself" , 
		    		"yourselves" , 
		    		"he" , 
		    		"him" , 
		    		"his" , 
		    		"himself" , 
		    		"she" , 
		    		"her" , 
		    		"hers" , 
		    		"herself" , 
		    		"it" , 
		    		"its" , 
		    		"itself" , 
		    		"they" , 
		    		"them" , 
		    		"their" , 
		    		"theirs" , 
		    		"themselves" , 
		    		"what" , 
		    		"which" , 
		    		"who" , 
		    		"whom" , 
		    		"this" , 
		    		"that" , 
		    		"these" , 
		    		"those" , 
		    		"am" , 
		    		"is" , 
		    		"are" , 
		    		"was" , 
		    		"were" , 
		    		"be" , 
		    		"been" , 
		    		"being" , 
		    		"have" , 
		    		"has" , 
		    		"had" , 
		    		"having" , 
		    		"do" , 
		    		"does" , 
		    		"did" , 
		    		"doing" , 
		    		"a" , 
		    		"an" , 
		    		"the" , 
		    		"and" , 
		    		"but" , 
		    		"if" , 
		    		"or" , 
		    		"because" , 
		    		"as" , 
		    		"until" , 
		    		"while" , 
		    		"of" , 
		    		"at" , 
		    		"by" , 
		    		"for" , 
		    		"with" , 
		    		"about" , 
		    		"against" , 
		    		"between" , 
		    		"into" , 
		    		"through" , 
		    		"during" , 
		    		"before" , 
		    		"after" , 
		    		"above" , 
		    		"below" , 
		    		"to" , 
		    		"from" , 
		    		"up" , 
		    		"down" , 
		    		"in" , 
		    		"out" , 
		    		"on" , 
		    		"off" , 
		    		"over" , 
		    		"under" , 
		    		"again" , 
		    		"further" , 
		    		"then" , 
		    		"once" , 
		    		"here" , 
		    		"there" , 
		    		"when" , 
		    		"where" , 
		    		"why" , 
		    		"how" , 
		    		"all" , 
		    		"any" , 
		    		"both" , 
		    		"each" , 
		    		"few" , 
		    		"more" , 
		    		"most" , 
		    		"other" , 
		    		"some" , 
		    		"such" , 
		    		"no" , 
		    		"nor" , 
		    		"not" , 
		    		"only" , 
		    		"own" , 
		    		"same" , 
		    		"so" , 
		    		"than" , 
		    		"too" , 
		    		"very" , 
		    		"s" , 
		    		"t" , 
		    		"can" , 
		    		"will" , 
		    		"just" , 
		    		"don" , 
		    		"should" , 
		    		"now",
		    		"its" , 
					"total" , 
					"time" , 
					"being" , 
					"each" ,  
					"managed" , 
					"which" ,  
					"type" , 
					"ensure" , 
					"pay" , 
					"that" , 
					"they" , 
					"also" , 
					"some" , 
					"though" , 
					"said" , 
					"over" , 
					"still" , 
					"meanwhile" , 
					"would" ,  
					"certainly" , 
					"whole" , 
					"made" , 
					"make" , 
					"follows");
		    result = new StopFilter(result, StopFilter.makeStopSet(stopList));
		    result = new PorterStemFilter(result);
		    return new TokenStreamComponents(source, result);

	}
}